# Hosts
---
 leaf1:
   hostname: 192.168.127.12
   groups:
     - spine

 spine1:
   hostname: 192.168.127.11
   groups:
     - leaf

 IOS2:
   hostname: 192.168.127.42
   groups:
     - IOS

 IOS3:
   hostname: 192.168.127.43
   groups:
     - IOS

 IOS4:
   hostname: 192.168.127.44
   groups:
     - IOS
